# Values for the vault-wrapper chart

# Values passed to the 'vault' subchart (dependency)
vault:
  # Run Vault in development mode (single node, in-memory storage - NOT FOR PRODUCTION)
  server:
    dev:
      enabled: true

    # Ensure HA mode is disabled when running in dev mode
    ha:
      enabled: false
      # raft: # Raft is the default integrated storage, disable if using dev mode
      #   enabled: false

    # Configure Ingress for the UI
    ingress:
      enabled: true
      ingressClassName: traefik # Use this if you have a default IngressClass
      annotations:
        # Use Traefik's websecure entrypoint for HTTPS
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        # Enable TLS termination at the router (Traefik handles certs)
        traefik.ingress.kubernetes.io/router.tls: "true"
        # Vault UI backend service uses HTTP (port 8200)
        # traefik.ingress.kubernetes.io/service.scheme: http # Usually not needed
      hosts:
        - host: vault.localhost

