apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer # Use domain-qualified finalizer
spec:
  project: default
  source:
    # Source is the Git repository containing this Application manifest and the wrapper chart
    repoURL: https://github.com/gergelysotidm/data-platform-stack.git # Ensure this is your repo URL
    path: argo/apps/200-airflow # Path to the wrapper chart directory within the Git repo
    targetRevision: HEAD # Or your specific branch/tag

    # Helm configuration for the wrapper chart
    helm:
      releaseName: airflow
      # Values file is implicitly values.yaml within the source path
  destination:
    server: https://kubernetes.default.svc
    namespace: services # Deploy Airflow into the services namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Ensure the services namespace is created
